export const constants = {
    HUB_URL: "",
    CURRENT_USER_KEY: "CURRENT_USER_KEY",
    STORAGE_KEY: "[SecretSantaApp] STORAGE_KEY",
    ACCESS_TOKEN_KEY: "ACCESS_TOKEN_KEY",
    LOGIN_CREDENTIALS: "LOGIN_CREDENTIALS",
    CURRENT_PROFILE_KEY: "CURRENT_PROFILE_KEY",
    CURRENT_TEAM_KEY: "CURRENT_TEAM_KEY",
    TENANT: "TENANT",
    CORRELATION_IDS_KEY: "CORRELATION_IDS_KEY"
};